### ISSUE TITLE
AT+IPR= command terminated with CR LF causes wdt reset

### ISSUE THREAD

**Issue by igrr** [igrr/atproto#9]
Trailing LF is not handled correctly after baud rate is changed. Probably need to flush rx buffer.

**Comment by martinayotte** [comment]
Hi igrr,
I' ve downloaded the latest atproto this morning, compiled it, flashed it, play with it doing queries, they worked fine. But as soon as I try to do something like AT+IPR=xxx or AT+CWMODE=x, I' ve got the symptom since I was using my picocom with option --omap crcrlf. I' ve then discovered that it was this CRLF issue causing wdt reset. So is it means that there are other places in the code that needs fixes ?

**Comment by igrr** [comment]
I have only been able to reproduce this with +IPR, not with +CWMODE. The issue is not related to the command itself, it's something in the dce command handling code.
Need to find a way to reproduce this with other commands.

**Comment by martinayotte** [comment]
Hi again,
With +CWMODE, the issue is probably intermittant because reading your reply, I've tried it again and it worked. But I still have in my shell the history of when it happened (but not able to repro anymore) :

AT+CWMODE=3
 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x40100000, len 23448, room 16 
tail 8
chksum 0xd6
load 0x3ffe8000, len 2644, room 0 
tail 4
chksum 0x6c
load 0x3ffe8a60, len 8420, room 4 
tail 0
chksum 0x6c
csum 0x6c

ERROR
AT+CWMODE?
+CWMODE:2
AT+CWMODE=3
 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x40100000, len 23448, room 16 
tail 8
chksum 0xd6
load 0x3ffe8000, len 2644, room 0 
tail 4
chksum 0x6c
load 0x3ffe8a60, len 8420, room 4 
tail 0
chksum 0x6c
csum 0x6c
AT+CWMODE?
+CWMODE:2
